### Listar todos os cursos
@baseUrl = https://humble-umbrella-jp6vp69qx76cpg4g-8080.app.github.dev/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBUEkgQ3Vyc29zIiwic3ViIjoidGVzdGUzQHRlc3RlLmNvbSIsImlkIjoyLCJleHAiOjE3NDkwNjg2OTZ9.j-7o-NM72D4r60N6ILKmD9SM8pI3ite7PGpyUdn9OFo
###

GET {{baseUrl}}/cursos
Authorization: Bearer {{token}}


### Obter curso por ID
GET {{baseUrl}}/cursos/2
Authorization: Bearer {{token}}


### Criar novo curso
POST {{baseUrl}}/cursos
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Curso de Java",
  "descricao": "Aprenda Java do básico ao avançado",  
  "cargaHoraria": 40
}

### Atualizar curso
PUT {{baseUrl}}/cursos/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Curso de Java Atualizado",
  "descricao": "Atualização do curso de Java",
    "cargaHoraria": 48
}


### Deletar curso
DELETE {{baseUrl}}/cursos/3
Authorization: Bearer {{token}}
